version: '3.8'
services:
  db:
    image: postgres:16
    container_name: todos_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - todo_network  

  backend:
    build: 
      context: ./backend   
      dockerfile: ../.docker/backend.Dockerfile
    container_name: todos_backend
    environment:
      - DB_HOST=db     
      - DB_PORT=5432   
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - todo_network

volumes:
  postgres_data:

networks:
  todo_network:
    driver: bridge